Locks and Multi fan-in and fan-out
JdeRobot/VisualCircuit pull request #195
Opened 2022-10-25 11:47 UTC by Suhas-G

Issues:
Locks: When multiple writers are writing to same wire, its necessary to lock the shared memory while write is in progress.
Enable in FSM: In the case of FSMs, a block should be able to disable itself after it transitions to the next state. But the Enable wire of a block is an input block and not writeable by it. This PR changes this by giving a separate interface for enable wire as a property of the inputs block. And also allows the block to disable by setting `inputs.enable = False` to disable itself safely. 
Multi Fan-in and Fan-out: When we have the scenario of multiple wires going to same input or same output having multiple wires to different inputs, we have to use the same underlying shared memory so that data can be modified correctly.

2022-10-27 08:28 UTC, toshan-luktuke requested changes
Tested with:
- [x] Multiple inputs (2 - 3 wires coming in a single block)
- [x] Multiple outputs (2 - 3 wires going out of a single block)

Remaining:
- [ ] FSM Testing with Enable

2022-10-27 08:36 UTC, Suhas-G commented on backend/staticfiles/synthesis/main.py
> +            names[name]["lock"].release()
Yes. Thanks. I'll change that.

2022-10-27 09:33 UTC, toshan-luktuke commented
I'm not able to figure out how the `enable` implementation is intended to work, I got it working but I had to make a few changes to the code here and there.
If possible can you give an example of the intended way to use it?

2022-11-04 11:19 UTC, Suhas-G commented
Did the fsm structure with enable I showed work? Shall I merge this PR?

2022-11-04 12:41 UTC, toshan-luktuke commented
Let's merge `outputs.py` and `main.py`. I've made some modifications to `inputs.py` to write to the Shared Memory like we discussed. Its better if I make a separate PR for that

2022-11-04 12:41 UTC, toshan-luktuke approved these changes

2022-11-10 15:10 UTC, merged